#include <stdio.h>
int main(){
    printf("abaababaabaababaababaabaababaabaababaababaabaababa\nababaabaababaabaababaababaabaababaabaababaababaaba\nababaababaabaababaabaababaababaabaababaababaabaaba\nbaabaababaababaabaababaabaababaababaabaababaababaa\nbaababaabaababaababaabaababaabaababaababaabaababaa\nbabaabaababaabaababaababaabaababaababaabaababaabaa\nbabaababaabaababaabaababaababaabaababaababaabaabab\n");
}
